version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mekaaz
      POSTGRES_PASSWORD: mekaazpassword
      POSTGRES_DB: mekaazdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://mekaaz:mekaazpassword@db:5432/mekaazdb
      REDIS_URL: redis://redis:6379
      SECRET_KEY: supersecretkey
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: 