- hosts: app
  become: yes
  vars:
    docker_image: "{{ docker_image }}"   # passed from GH Actions
    db_host: "{{ db_host }}"
    db_name: "{{ db_name }}"
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
    secret_key: "{{ secret_key }}"
  tasks:
    - name: Update apt
      apt: { update_cache: yes }

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure docker running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull redis image
      community.docker.docker_image:
        name: redis:7-alpine
        source: pull

    - name: Run redis container (if not exists)
      community.docker.docker_container:
        name: redis
        image: redis:7-alpine
        state: started
        restart_policy: always
        published_ports:
          - "6379:6379"

    - name: Pull FastAPI image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Stop old app container (if exists)
      community.docker.docker_container:
        name: fastapi_app
        state: absent
      ignore_errors: yes

    - name: Run FastAPI container
      community.docker.docker_container:
        name: fastapi_app
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "80:8000"
        env:
          DATABASE_URL: "postgresql+psycopg2://{{ db_user }}:{{ db_password }}@{{ db_host }}:5432/{{ db_name }}"
          REDIS_URL: "redis://redis:6379"
          SECRET_KEY: "{{ secret_key }}"